Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"
  config.vm.synced_folder ".", "/app"
  config.vm.provision "shell", inline: "/app/bin/install-ansible.sh", upload_path: "/home/vagrant/install-ansible.sh"
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "/app/ansible/local.yml"
  end
  config.vm.provision "shell", inline: "/app/bin/scan.sh", upload_path: "/home/vagrant/scan.sh"
end
