---
# Use ansible to provision hosts

# Thanks https://www.tricksofthetrades.net/2017/10/02/ansible-local-playbooks/ for
# the trick on installing locally using "hosts: 127.0.0.1" and "connection:local"

- name: Install SSM Agent
  hosts: 127.0.0.1
  connection: local
  become: yes
  roles: 
    - ssm-agent

- name: Install New Relic Infrastructure
  hosts: 127.0.0.1
  connection: local
  become: yes
  roles: 
    - newrelic.newrelic-infra
  vars:
    nrinfragent_os_name: CentOS
    nrinfragent_os_version: 7
    nrinfragent_config:
      license_key: ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
      log_file: /var/log/newrelic-infra/nr-infra.log
      log_to_stdout: false

- name: Install Web Application
  hosts: 127.0.0.1
  connection: local
  become: yes
  roles:
    - nginxinc.nginx
    - prepare-web-content
    - prepare-codedeploy


- name: Harden Server
  hosts: 127.0.0.1
  connection: local
  become: yes
  roles:
    - extra-cis-remediation
    #- MindPointGroup.RHEL7-CIS
    - scan-openscap
