---
# tasks file for scan-gauntlt


- name: Ensure build directory exists
  file:
    path: "{{ build_dir }}"
    state: directory
    mode: 0775

- name: Scan using gauntlt
  command: gauntlt -f html -o "{{ output_file_html }}" "{{ gauntlt_attacks }}"
