---
# tasks file for scan-gauntlt


- name: Ensure build directory exists
  file:
    path: "{{ build_dir }}"
    state: directory
    mode: 0775

- name: Scan using gauntlt
  shell: gauntlt "{{ gauntlt_attacks }}" | cat >> "{{ build_dir}}""{{ output_file_html }}" 
